version: "3.9"

services:
  mongodb:
    image: mongo:latest
    networks:
      - myapp
    volumes:
      - db_data:/data/db
    deploy:
      placement:
        constraints:
          - node.labels.workload==abc
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "example"
    ports:
      - 27017:27017
  nodeapp:
    depends_on:
      - mongodb
    image: tieungao1988/task9:v1
    ports:
      - 8000:3000
    environment:
      MONGODB_URI: "root:example@mongodb://mongodb:27017/demo"
      PORT: 3000
    networks:
      - myapp
    deploy:
      replicas: 2
networks:
  myapp:
    driver: overlay
volumes:
  db_data: {}