version: "3.9"

services:
  mongodb:
    image: mongo:latest
    # networks:
    #   - myapp
    volumes:
      - db_data:/data/db:rw
    environment:
      - "constraint:node==ubuntu02"

# networks:
  # myapp:
  #   driver: overlay
volumes:
  db_data: {}