version: "3.9"

services:
  mongodb:
    image: mongo:latest
    networks:
      - myapp
    volumes:
      - db_data:/data/db
    deploy:
      placement:
        constraints:
          - node.labels.workload==abc
    environment:
      # - "constraint:node==ubuntu02"
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "example"
  nodeapp:
    image: tieungao1988/task9:v1
    ports:
      - 8000:3000
    environment:
      MONGODB_URI: "mongodb://root:example@mongodb:27017/"
      PORT: 3000
    networks:
      - myapp
networks:
  myapp:
    driver: overlay
volumes:
  db_data: {}