version: "3.9"

services:
  mongodb:
    image: mongo:latest
    volumes:
      - data_dir:/mongo:latest
  nodejs:
    depends_on:
      - mongodb
    image: task6
    ports:
      - "8000:3000"
    environment:
      MONGODB_URI: "mongodb://mongodb:27017/demo"
      PORT: 3000

volumes:
  data_dir: {}